name = "Minecraft1.21.1Packwiz"
author = "mdjnico"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eb80d12555d03908f25c127bd5509a9ace4956df61ab2ef8794d5ce203f1291"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
