name = "Minecraft1.21.1Packwiz"
author = "mdjnico"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f16ffe46b1b1ca3d9b57d810741193845b1bb7bb0cbf4dfa0a2ebd207f8f219a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
