name = "Minecraft1.21.1Packwiz"
author = "mdjnico"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "785b65d2a309acea1401f3c30736b3b0babdf85ed1852c595e826406e9c6e8de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
